### ISSUE TITLE
Need improvement...

### ISSUE THREAD

**Issue by Vitoshka** [GritsUI/ManaMinder#1]
Сan you make the settings for moving the notification icon on the screen?

thx)

**Comment by GritsUI** [comment]
Good suggestion, I've been meaning to get that added. I should be able to get it in some time this weekend.

**Comment by GritsUI** [comment]
This has been added in [Version 1.3](https://github.com/GritsUI/ManaMinder/releases/tag/v1.3) or the latest from master.
