### ISSUE TITLE
Need improvement

### ISSUE THREAD

**Issue by Vitoshka** [GritsUI/ManaMinder#9]
Can you add a feature to the addon - **fake/test mode the full frame** to help orient it. This would be very convenient when setting up the display. thx

**Comment by GritsUI** [comment]
A "Show Test Bars" option has been added under the bars configuration section that shows bars with the different possible states to help with this.

Available in [Version 1.5](https://github.com/GritsUI/ManaMinder/releases/tag/v1.5) or latest from master.
